version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db_project

    ports:
      - '8080:8080'

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"