version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: db_hw_2

    ports:
      - '8080:8080'

    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"